services:
  - type: web
    name: rankcatalyst-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /api/quizzes/chapters/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: rankcatalyst-backend.onrender.com
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rankcatalyst-db
          property: connectionString

databases:
  - name: rankcatalyst-db
    plan: free
    databaseName: rankcatalyst
    user: rankcatalyst_user

